version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE_NAME}
    restart: always
    env_file:
      - ${ENV_FILE:-../.env}
    ports:
      - ${EXPOSED_PORT:-4000}:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
