/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthusersUsersImport } from './routes/_auth/(users)/users'
import { Route as AuthusersCreateCoacheeImport } from './routes/_auth/(users)/create-coachee'
import { Route as AuthprofileProfileImport } from './routes/_auth/(profile)/profile'
import { Route as AuthnotesNotesImport } from './routes/_auth/(notes)/notes'
import { Route as AuthdashboardDashboardImport } from './routes/_auth/(dashboard)/dashboard'
import { Route as AuthcalendarCalendarImport } from './routes/_auth/(calendar)/calendar'
import { Route as AuthappointmentsAppointmentsImport } from './routes/_auth/(appointments)/appointments'
import { Route as AuthnotesnotesIdNoteDetailImport } from './routes/_auth/(notes)/[notesId]/NoteDetail'
import { Route as AuthappointmentsappointmentIdReviewImport } from './routes/_auth/(appointments)/[appointmentId]/review'
import { Route as AuthappointmentscreateCreateImport } from './routes/_auth/(appointments)/(create)/create'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthusersUsersRoute = AuthusersUsersImport.update({
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)

const AuthusersCreateCoacheeRoute = AuthusersCreateCoacheeImport.update({
  path: '/create-coachee',
  getParentRoute: () => AuthRoute,
} as any)

const AuthprofileProfileRoute = AuthprofileProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)

const AuthnotesNotesRoute = AuthnotesNotesImport.update({
  path: '/notes',
  getParentRoute: () => AuthRoute,
} as any)

const AuthdashboardDashboardRoute = AuthdashboardDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthcalendarCalendarRoute = AuthcalendarCalendarImport.update({
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)

const AuthappointmentsAppointmentsRoute =
  AuthappointmentsAppointmentsImport.update({
    path: '/appointments',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthnotesnotesIdNoteDetailRoute = AuthnotesnotesIdNoteDetailImport.update(
  {
    path: '/[notesId]/NoteDetail',
    getParentRoute: () => AuthRoute,
  } as any,
)

const AuthappointmentsappointmentIdReviewRoute =
  AuthappointmentsappointmentIdReviewImport.update({
    path: '/[appointmentId]/review',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthappointmentscreateCreateRoute =
  AuthappointmentscreateCreateImport.update({
    path: '/create',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/(appointments)/appointments': {
      id: '/_auth/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthappointmentsAppointmentsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(calendar)/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthcalendarCalendarImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(dashboard)/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthdashboardDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(notes)/notes': {
      id: '/_auth/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthnotesNotesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(profile)/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthprofileProfileImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(users)/create-coachee': {
      id: '/_auth/create-coachee'
      path: '/create-coachee'
      fullPath: '/create-coachee'
      preLoaderRoute: typeof AuthusersCreateCoacheeImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(users)/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthusersUsersImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(appointments)/(create)/create': {
      id: '/_auth/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthappointmentscreateCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(appointments)/[appointmentId]/review': {
      id: '/_auth/[appointmentId]/review'
      path: '/[appointmentId]/review'
      fullPath: '/[appointmentId]/review'
      preLoaderRoute: typeof AuthappointmentsappointmentIdReviewImport
      parentRoute: typeof AuthImport
    }
    '/_auth/(notes)/[notesId]/NoteDetail': {
      id: '/_auth/[notesId]/NoteDetail'
      path: '/[notesId]/NoteDetail'
      fullPath: '/[notesId]/NoteDetail'
      preLoaderRoute: typeof AuthnotesnotesIdNoteDetailImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthappointmentsAppointmentsRoute: typeof AuthappointmentsAppointmentsRoute
  AuthcalendarCalendarRoute: typeof AuthcalendarCalendarRoute
  AuthdashboardDashboardRoute: typeof AuthdashboardDashboardRoute
  AuthnotesNotesRoute: typeof AuthnotesNotesRoute
  AuthprofileProfileRoute: typeof AuthprofileProfileRoute
  AuthusersCreateCoacheeRoute: typeof AuthusersCreateCoacheeRoute
  AuthusersUsersRoute: typeof AuthusersUsersRoute
  AuthappointmentscreateCreateRoute: typeof AuthappointmentscreateCreateRoute
  AuthappointmentsappointmentIdReviewRoute: typeof AuthappointmentsappointmentIdReviewRoute
  AuthnotesnotesIdNoteDetailRoute: typeof AuthnotesnotesIdNoteDetailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthappointmentsAppointmentsRoute: AuthappointmentsAppointmentsRoute,
  AuthcalendarCalendarRoute: AuthcalendarCalendarRoute,
  AuthdashboardDashboardRoute: AuthdashboardDashboardRoute,
  AuthnotesNotesRoute: AuthnotesNotesRoute,
  AuthprofileProfileRoute: AuthprofileProfileRoute,
  AuthusersCreateCoacheeRoute: AuthusersCreateCoacheeRoute,
  AuthusersUsersRoute: AuthusersUsersRoute,
  AuthappointmentscreateCreateRoute: AuthappointmentscreateCreateRoute,
  AuthappointmentsappointmentIdReviewRoute:
    AuthappointmentsappointmentIdReviewRoute,
  AuthnotesnotesIdNoteDetailRoute: AuthnotesnotesIdNoteDetailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/appointments': typeof AuthappointmentsAppointmentsRoute
  '/calendar': typeof AuthcalendarCalendarRoute
  '/dashboard': typeof AuthdashboardDashboardRoute
  '/notes': typeof AuthnotesNotesRoute
  '/profile': typeof AuthprofileProfileRoute
  '/create-coachee': typeof AuthusersCreateCoacheeRoute
  '/users': typeof AuthusersUsersRoute
  '/create': typeof AuthappointmentscreateCreateRoute
  '/[appointmentId]/review': typeof AuthappointmentsappointmentIdReviewRoute
  '/[notesId]/NoteDetail': typeof AuthnotesnotesIdNoteDetailRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/appointments': typeof AuthappointmentsAppointmentsRoute
  '/calendar': typeof AuthcalendarCalendarRoute
  '/dashboard': typeof AuthdashboardDashboardRoute
  '/notes': typeof AuthnotesNotesRoute
  '/profile': typeof AuthprofileProfileRoute
  '/create-coachee': typeof AuthusersCreateCoacheeRoute
  '/users': typeof AuthusersUsersRoute
  '/create': typeof AuthappointmentscreateCreateRoute
  '/[appointmentId]/review': typeof AuthappointmentsappointmentIdReviewRoute
  '/[notesId]/NoteDetail': typeof AuthnotesnotesIdNoteDetailRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/appointments': typeof AuthappointmentsAppointmentsRoute
  '/_auth/calendar': typeof AuthcalendarCalendarRoute
  '/_auth/dashboard': typeof AuthdashboardDashboardRoute
  '/_auth/notes': typeof AuthnotesNotesRoute
  '/_auth/profile': typeof AuthprofileProfileRoute
  '/_auth/create-coachee': typeof AuthusersCreateCoacheeRoute
  '/_auth/users': typeof AuthusersUsersRoute
  '/_auth/create': typeof AuthappointmentscreateCreateRoute
  '/_auth/[appointmentId]/review': typeof AuthappointmentsappointmentIdReviewRoute
  '/_auth/[notesId]/NoteDetail': typeof AuthnotesnotesIdNoteDetailRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/appointments'
    | '/calendar'
    | '/dashboard'
    | '/notes'
    | '/profile'
    | '/create-coachee'
    | '/users'
    | '/create'
    | '/[appointmentId]/review'
    | '/[notesId]/NoteDetail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/appointments'
    | '/calendar'
    | '/dashboard'
    | '/notes'
    | '/profile'
    | '/create-coachee'
    | '/users'
    | '/create'
    | '/[appointmentId]/review'
    | '/[notesId]/NoteDetail'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/appointments'
    | '/_auth/calendar'
    | '/_auth/dashboard'
    | '/_auth/notes'
    | '/_auth/profile'
    | '/_auth/create-coachee'
    | '/_auth/users'
    | '/_auth/create'
    | '/_auth/[appointmentId]/review'
    | '/_auth/[notesId]/NoteDetail'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/appointments",
        "/_auth/calendar",
        "/_auth/dashboard",
        "/_auth/notes",
        "/_auth/profile",
        "/_auth/create-coachee",
        "/_auth/users",
        "/_auth/create",
        "/_auth/[appointmentId]/review",
        "/_auth/[notesId]/NoteDetail"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/appointments": {
      "filePath": "_auth/(appointments)/appointments.tsx",
      "parent": "/_auth"
    },
    "/_auth/calendar": {
      "filePath": "_auth/(calendar)/calendar.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard": {
      "filePath": "_auth/(dashboard)/dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/notes": {
      "filePath": "_auth/(notes)/notes.tsx",
      "parent": "/_auth"
    },
    "/_auth/profile": {
      "filePath": "_auth/(profile)/profile.tsx",
      "parent": "/_auth"
    },
    "/_auth/create-coachee": {
      "filePath": "_auth/(users)/create-coachee.tsx",
      "parent": "/_auth"
    },
    "/_auth/users": {
      "filePath": "_auth/(users)/users.tsx",
      "parent": "/_auth"
    },
    "/_auth/create": {
      "filePath": "_auth/(appointments)/(create)/create.tsx",
      "parent": "/_auth"
    },
    "/_auth/[appointmentId]/review": {
      "filePath": "_auth/(appointments)/[appointmentId]/review.tsx",
      "parent": "/_auth"
    },
    "/_auth/[notesId]/NoteDetail": {
      "filePath": "_auth/(notes)/[notesId]/NoteDetail.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
